Update Dockerfile
WildMeOrg/scout pull request #77
Opened 2024-04-04 21:28 UTC by tsubramanian

Docker build fails : as the issue mentioned here :https://github.com/WildMeOrg/scout/issues/76
PR fixes 76

**Changes**
- added the timeout for pip

2024-04-10 20:38 UTC, TanyaStere42 requested changes
I think the option needs to be --timeout, not --default-timeout. It looks like this standard has updated

2024-04-10 20:44 UTC, TanyaStere42 reviewed
Just a question: Is there a reason to have `future` in this pip install?

2024-04-10 22:34 UTC, tsubramanian commented
> Just a question: Is there a reason to have `future` in this pip install?

I have removed it. It is not required here.

2024-04-12 17:52 UTC, TanyaStere42 approved these changes

2024-04-12 17:53 UTC, merged